version: '3.2'
services:
  api-public-bank-reconciliation:
    image: api-public-bank-reconciliation
    build: api-public-bank-reconciliation
    depends_on:
      - bank_reconciliation_db
    ports:
      - "8000:3000"
    volumes:
      - ./src:/home/app/src
    environment:
      DB_HOST: bank_reconciliation_db
      DB_USER: user
      DB_PASSWORD: secret
      DB_NAME: bank_reconciliation
      
  api-private-bank-reconciliation:
    image: api-private-bank-reconciliation
    build: api-private-bank-reconciliation
    depends_on:
      - bank_reconciliation_db
    volumes:
      - ./src:/home/app/src
    environment:
      DB_HOST: bank_reconciliation_db
      DB_USER: user
      DB_PASSWORD: secret
      DB_NAME: bank_reconciliation
      
  bank_reconciliation_db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: bank_reconciliation
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    expose:
      - "3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - bank_reconciliation_db
    ports:
      - "8888:80"
    environment:
      PMA_HOST: bank_reconciliation_db
      MYSQL_ROOT_PASSWORDL: secret
    links:
      - bank_reconciliation_db
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
volumes:
  db_data: {}